
//var declaration

var oneVar;
var twoVar;
var threeVar;
var fourVar;
var fiveVar;
var sixVar;
var sevenVar;
var eightVar;
var nineVar;
var tenVar;
var elevenVar;
var twelveVar;
var thirteenVar;
var fourteenVar;
var fifteenVar;
var sixteenvar;
var seventeenVar;
var eighteenVar;
var nineteenVar;
var twentyVar;
var twentyoneVar;
var twentytwoVar;
var twentyThreeVar;
var twentyFourVar;
var twentyFiveVar;
var twentySixVar;
var twentySevenVar;
var twentyEightVar;
var twentyNineVar;
var thirtyVar;
var thirtyOneVar;
var thirtyTwoVar;
var thirtyThreeVar;
var thirtyFourVar;
var thirtyfiveVar;
var thirtySixVar;
var thirtySevenVar;
var thirtyEightVar;
var thirtyNineVar;
var fortyVar;
var fortyOneVar;
var fortyTwoVar;
var fortyThreeVar;
var fortyFourVar;
var fortyFiveVar;
var fortySixVar;
var fortySevenVar;
var fortyEightVar;



// let declaration


let onelet;
let twolet;
let threelet;
let fourlet;
let fivelet;
let sixlet;
let sevenlet;
let eightlet;
let ninelet;
let tenlet;
let elevenlet;
let twelvelet;
let thirteenlet;
let fourteenlet;
let fifteenlet;
let sixteenlet;
let seventeenlet;
let eighteenlet;
let nineteenlet;
let twentylet;
let twentyonelet;
let twentytwolet;
let twentyThreelet;
let twentyFourlet;
let twentyFivelet;
let twentySixlet;
let twentySevenlet;
let twentyEightlet;
let twentyNinelet;
let thirtylet;
let thirtyOnelet;
let thirtyTwolet;
let thirtyThreelet;
let thirtyFourlet;
let thirtyfivelet;
let thirtySixlet;
let thirtySevenlet;
let thirtyEightlet;
let thirtyNinelet;
let fortylet;
let fortyOnelet;
let fortyTwolet;
let fortyThreelet;
let fortyFourlet;
let fortyFivelet;
let fortySixlet;
let fortySevenlet;
let fortyEightlet;


//const initialization

const oneconst = "theone";
const twoconst = "thetwo";
const threeconst = 23;
const fourconst = "retro";
const fiveconst = "surya";
const sixconst = "pathavaikum";
const sevenconst = "paaarvaikara";
const eightconst = "eadhuuu";
const nineconst = "naagarjunaa va";
const tenconst = "ianaadhu";
const elevenconst = "rolex";
const twelveconst = "narayana";
const thirteenconst = "raju";
const fourteenconst = "ahhh";
const fifteenconst = "vaazhthukkal";
const sixteenconst = "vaaazhthukkal";
const seventeenconst = "32";
const eighteenconst = 45;
const nineteenconst = 98;
const twentyconst = 78;
const twentyoneconst = "browwww";
const twentytwoconst = "veeriyavarthu";
const twentyThreeconst = "broww";
const twentyFourconst = "sethurven naanu";
const twentyFiveconst = "epdi bro thokalmm";
const twentySixconst = "88";
const twentySevenconst = 90;
const twentyEightconst = 424;
const twentyNineconst = 7676;
const thirtyconst = 999;
const thirtyOneconst = 65;
const thirtyTwoconst = 8787;
const thirtyThreeconst = 90909;
const thirtyFourconst = 2222;
const thirtyfiveconst = 4444;
const thirtySixconst = 7766;
const thirtySevenconst = 1091;
const thirtyEightconst = 265;
const thirtyNineconst = 2828;
const fortyconst = 65655;
const fortyOneconst = 9;
const fortyTwoconst = 888;
const fortyThreeconst =456;
const fortyFourconst = 46544;
const fortyFiveconst = "umma";
const fortySixconst = "vainko ";
const fortySevenconst = 88;
const fortyEightconst = 242424242;
